---
kind: Service
apiVersion: v1
metadata:
  name: chat
spec:
  type: LoadBalancer
  selector:
    app: chat
  ports:
    - name: http
      protocol: TCP
      port: 6969
      targetPort: chat-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: edwardsuwirya/kampret:chat1.0
        ports:
        - name: chat-port
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: regcred 
